### ISSUE TITLE
Create, Update, and Delete Service in ServiceClient

### ISSUE THREAD

**Issue by m4dcoder** [harness/harness-go-sdk#108]
Can create, update, and delete functions be added to the new ServiceClient @ https://github.com/harness/harness-go-sdk/blob/main/harness/cd/service.go? There is upsert and delete in the ConfigAsCode client. Seems inconsistent to switch between the Service client and CAC client.

**Comment by micahlmartin** [comment]
Unfortunately these methods aren't supported in our GraphQL API's. These are the kinds of inconsistencies that I built the Terraform provider to address. It abstracts away the need for the consumer to know which API to use in which scenario. Also, there's not an easy way to use the ConfigAsCode client to list and filter services. Totally agree this is less than ideal. I'll file a ticket with the API team to try and get this addressed.
