### ISSUE TITLE
ArtifactorySource is not populated in GraphQL Service

### ISSUE THREAD

**Issue by m4dcoder** [harness/harness-go-sdk#111]
The GraphQL Service has ArtifactorySources attribute however it is not populated on get. Also, there is no method to get the list of artifacts collected for a source.

**Comment by micahlmartin** [comment]
Will be releasing this fix shortly https://github.com/harness/harness-go-sdk/commit/a66a5c4a3f3b3dba4f7134224fbcb1fd6a051a02

**Comment by micahlmartin** [comment]
Fixed in v0.1.21
