### ISSUE TITLE
Unable to create inline text secret

### ISSUE THREAD

**Issue by rumstead** [harness/harness-go-sdk#120]
I see the [SecretTextSpec struct](https://github.com/harness/harness-go-sdk/search?q=SecretTextSpec) which I believe is what I need to create an inline text secret. However, the [secret APIs](https://github.com/harness/harness-go-sdk/blob/34738eba5a1332733773afabd17ad45fa1a20404/harness/nextgen/api_secrets.go) only accepts the [SecretRequestWrapper ](https://github.com/harness/harness-go-sdk/blob/34738eba5a1332733773afabd17ad45fa1a20404/harness/nextgen/model_secret_request_wrapper.go)-> [Secret](https://github.com/harness/harness-go-sdk/blob/34738eba5a1332733773afabd17ad45fa1a20404/harness/nextgen/model_secret.go) -> [SecretSpec](https://github.com/harness/harness-go-sdk/blob/34738eba5a1332733773afabd17ad45fa1a20404/harness/nextgen/model_secret_spec.go). 

Do the clients just need to be rebuilt from the swagger definitions?

**Comment by micahlmartin** [comment]
@rumstead give this a shot in v0.1.26. Here's a test I added for reference https://github.com/harness/harness-go-sdk/blob/main/harness/nextgen/api_secrets_test.go. Let me know if you need anything else fixed.
