### ISSUE TITLE
Feature Request: Allow the client to set a next gen api key without setting a CD api key

### ISSUE THREAD

**Issue by eahrend** [harness/harness-go-sdk#80]
Currently if a user is just using next gen, and only has a next gen api key, they are still required to set a fake API key during sdk.NewSession().  This is because the current-gen client explicitly looks for an API key and returns an error if one is not set. 
https://github.com/harness-io/harness-go-sdk/blob/main/harness/cd/client.go#L54

Ideally, I should be able to use a current-gen key, a next-gen key, or both without any errors being thrown. 

Related to:
https://github.com/harness-io/terraform-provider-harness/pull/75#issuecomment-1029496764

**Comment by micahlmartin** [comment]
This currently does work if you just use the individual nextgen, or current gen clients. But in the Terraform provider we're using the `sdk.Session` which initializes both clients at the same time.

**Comment by micahlmartin** [comment]
got rid of the `session` object in the latest commit since we no longer need to combine the clients due to splitting up the provider into two separate projects.
