### ISSUE TITLE
Consistent type used for timestamps in models

### ISSUE THREAD

**Issue by m4dcoder** [harness/harness-go-sdk#96]
Can type used for timestamps be consistent and a type that doesn't cause error with json.Marshal?

Here are two examples that I'm working with. The Delegate LastHeartBeat is in string but the value is actual int64 which I have to convert to int64 first and then to time.Time manually. The CloudProvider CreatedAt is in *time.Time that returns pointer error on json.Marshal.
- Delegate LastHeartBeat is type of string @ https://github.com/harness/harness-go-sdk/blob/main/harness/cd/graphql/model_delegate.go#L11
- CloudProvider CreatedAt is type of *time.Time @ https://github.com/harness/harness-go-sdk/blob/main/harness/cd/graphql/types.go#L646

**Comment by micahlmartin** [comment]
Looking to address this with this commit https://github.com/harness/harness-go-sdk/commit/8bbb1e6b2e4b3f8760a64cb754a370fe52c670a5

**Comment by micahlmartin** [comment]
@m4dcoder published version v0.1.18. Let me know if this fixes the issue for you.
